version: '3.7'

networks:
  webnet:
volumes:
  mysqldb:
    driver: local
  redisdb:
    driver: local

services:
  app:
    restart: unless-stopped
    build:
      context: .
      args:
        - NODE_ENV=${APP_ENV}
        - NODE_VERSION=${APP_NODE_VERSION}
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 3001:3001
    command: npm run start:${APP_ENV}
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
      - redis
      - mysqldb

  redis:
    build:
      context: ./redis
    restart: unless-stopped
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_GUEST_PORT}
    volumes:
      - ${DATA_PATH}/redis:/data
    networks:
      - webnet
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]

  mysqldb:
    restart: unless-stopped
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/data
    ports:
      - 3305:3306
    networks:
      - webnet

  mongodb:
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_INIT_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGODB_APP_USER}
      - MONGO_INITDB_PASSWORD=${MONGODB_APP_PASSWORD}
    build:
      context: ./mongodb
      args:
        - PORT=${MONGODB_GUEST_PORT}
    ports:
      - ${MONGODB_HOST_PORT}:${MONGODB_GUEST_PORT}
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ${DATA_PATH}/mongo/db:/data/db:rw
      - ${DATA_PATH}/mongo/configdb:/data/configdb:rw
      - ${LOG_PATH}/mongo/:/var/log/mongodb:rw
    networks:
      - webnet
  
